// templates/vue-js/src/App.vue
<script setup>
import { ref } from 'vue';

const count = ref(0);
</script>

<template>
  <main class="app">
    <h1>Vue</h1>
    <button
      type="button"
      @click="count++"
    >
      count is {{ count }}
    </button>
    <p>
      Edit <code>src/App.vue</code> and save to test HMR.
    </p>
  </main>
</template>

<style scoped>
.app {
  max-width: 640px;
  margin: 0 auto;
  padding: 2rem;
  text-align: center;
  font-family: system-ui, sans-serif;
}

button {
  border-radius: 8px;
  border: 1px solid transparent;
  padding: 0.6em 1.2em;
  font-size: 1em;
  font-weight: 500;
  background-color: #1a1a1a;
  color: white;
  cursor: pointer;
}

button:hover {
  border-color: #42b883;
}
</style>

// templates/react-js/tailwind-overrides/src/App.jsx
import { useState } from 'react';

function App() {
  const [count, setCount] = useState(0);

  return (
    <main className="flex min-h-screen flex-col items-center justify-center gap-6 bg-slate-950 px-4 text-center text-slate-100">
      <h1 className="text-3xl font-bold tracking-tight">React</h1>
      <button
        type="button"
        onClick={() => setCount((c) => c + 1)}
        className="rounded-lg bg-cyan-600 px-5 py-2.5 font-medium text-white transition hover:bg-cyan-500"
      >
        count is {count}
      </button>
      <p className="text-sm text-slate-400">
        Edit <code className="rounded bg-slate-800 px-1.5 py-0.5 text-slate-200">src/App.jsx</code> and save to test HMR.
      </p>
    </main>
  );
}

export default App;
