// templates/react-ts/src/App.tsx
import { useState } from 'react';
import './App.css';

function App() {
  const [count, setCount] = useState(0);

  return (
    <main className="app">
      <h1>React + TypeScript</h1>
      <button type="button" onClick={() => setCount((c) => c + 1)}>
        count is {count}
      </button>
      <p>
        Edit <code>src/App.tsx</code> and save to test HMR.
      </p>
    </main>
  );
}

export default App;

// templates/angular-ts/src/app/app.component.ts
import { Component, signal } from '@angular/core';

@Component({
  selector: 'app-root',
  standalone: true,
  templateUrl: './app.component.html',
  styleUrl: './app.component.css',
})
export class AppComponent {
  protected readonly count = signal(0);

  increment(): void {
    this.count.update((value) => value + 1);
  }
}

<main class="app">
  <h1>Angular</h1>
  <button type="button" (click)="increment()">count is {{ count() }}</button>
  <p>Edit <code>src/app/app.component.ts</code> and save to test HMR.</p>
</main>
